global proc amDeformNode ()
{
	createNode test_node -n deformerNode;
	
	sphere -n sphere1 -r 1;

	connectAttr twist_node_1.angle 30;	
}

global proc amMenu ()
{
	global string $gMainWindow;
	menu -parent $gMainWindow -tearOff true -label "Twist" twistMenu;
		menuItem -label "Twist Geometry"
			-command "createTwist" twistMenuItem1;
}

// Run circleMenu to add "Circle" to the top level Maya menu list.
twistMenu;